### ISSUE TITLE
Add gitignore, and remove `node_modules` from the github

### ISSUE THREAD

**Issue by mt-sette** [M0hamedGard0ud/Central-Dogma_Project-CLI#2]
Steps to follow. 

1. create `.gitignore` file and add the entry for `node_modules`
2. delete `node_modules` directory locally, 
3. push changes to github.
4. `npm install` to recreate the node modules. 
5. check with `git status` if everything is done correctly

**Comment by M0hamedGard0ud** [comment]
Please Check out the recent updates that has been applied so far.

**Comment by mt-sette** [comment]
Nice :+1:
